# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='filelocation',
            field=models.CharField(max_length=255, null=True, verbose_name='filelocation'),
        ),
    ]
