# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0002_auto_20160205_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='datafile',
            field=models.FileField(max_length=10000, upload_to='/home/synadmin/Downloads/'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='filelocation',
            field=models.CharField(default=True, max_length=255, verbose_name='filelocation'),
        ),
    ]
