# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0005_auto_20160205_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='datafile',
            field=models.FileField(max_length=10000, upload_to=b''),
        ),
    ]
